#!/bin/bash
# Quick reference for using the optimized add_backgrounds

echo "========================================================================"
echo "OPTIMIZED add_backgrounds - Quick Reference"
echo "========================================================================"
echo ""
echo "PERFORMANCE IMPROVEMENT:"
echo "  File discovery: 5 minutes → 10 seconds (30x faster!)"
echo ""
echo "LOCATION:"
echo "  Executable: ./build/src/app/add_backgrounds"
echo "  Modified:   ./src/lib/utils.cpp (find_input_files function)"
echo ""
echo "USAGE (unchanged):"
echo "  ./scripts/add_backgrounds.sh -j <json_config> [options]"
echo ""
echo "  Or directly:"
echo "  ./build/src/app/add_backgrounds -j <json_config> [options]"
echo ""
echo "OPTIONS:"
echo "  -j, --json <file>    JSON configuration file (required)"
echo "  -s, --skip <N>       Skip N files at start"
echo "  -m, --max <N>        Process max N files"
echo "  -f, --override       Override existing output files"
echo "  -v, --verbose        Verbose output"
echo "  -d, --debug          Debug mode"
echo ""
echo "EXAMPLE:"
echo "  ./build/src/app/add_backgrounds \\"
echo "    -j ./json/es_fixed_myproc.json \\"
echo "    -m 20 --skip 100 -f"
echo ""
echo "VERIFICATION:"
echo "  Run this to test (processes 1 file only):"
echo "  ./build/src/app/add_backgrounds \\"
echo "    -j ./json/es_fixed_myproc.json -m 1 -s 0"
echo ""
echo "CONDOR JOBS:"
echo "  Your condor jobs will automatically use the optimized version"
echo "  after you push/sync the updated code."
echo ""
echo "TIMING BREAKDOWN (verified 2025-10-30):"
echo "  - Find 4520 signal files:     ~10 seconds (was 150s)"
echo "  - Find 346 background files:  <1 second  (was 141s)"
echo "  - Per-file processing:        ~40-50 seconds"
echo ""
echo "EXPECTED JOB IMPROVEMENTS:"
echo "  - Jobs save ~5 minutes at startup"
echo "  - More efficient use of compute resources"
echo "  - Faster overall pipeline execution"
echo ""
echo "========================================================================"
