# script to submit jobs to the grid for sn simulation

notify_user         = evilla@cern.ch
notification        = Error

JOBNAME             = process_files_cc-from4900to5000
executable          = /afs/cern.ch/work/e/evilla/private/dune/online-pointing-utils/scripts/sequence.sh
# using the arguments from below, not this line
output              = /afs/cern.ch/work/e/evilla/private/dune/online-pointing-utils/job_output/job.$(ClusterId).$(ProcId).$(JOBNAME).out
error               = /afs/cern.ch/work/e/evilla/private/dune/online-pointing-utils/job_output/job.$(ClusterId).$(ProcId).$(JOBNAME).err
log                 = /afs/cern.ch/work/e/evilla/private/dune/online-pointing-utils/job_output/job.$(ClusterId).$(JOBNAME).log
# request_cpus        = 1
# request_memory      = 2000

+JobFlavour         = "workday"

queue arguments from /afs/cern.ch/work/e/evilla/private/dune/online-pointing-utils/condor/evilla/list_of_jobs.txt
