#ifndef TRUEPARTICLE_H
#define TRUEPARTICLE_H

#include <vector>
#include <iostream>
#include <climits>

#include <Logger.h> 

#include <Neutrino.h>

LoggerInit([]{ Logger::getUserHeader() << "[" << FILENAME << "]"; });


// both particles from neutrino interactions and backgrounds
// will have a TrueParticle object
// Regardless wheter they are generated by the generator or by geant4, we don't care

class TrueParticle {
    
    public:
        // constructor
        TrueParticle(
            int event, 
            float x,
            float y,
            float z,
            float Px,
            float Py,
            float Pz,
            float energy,
            std::string generator_name,
            int pdg,
            std::string process,
            int track_id = -1,
            int truth_id = -1
        ) :
            event(event),
            x(x),
            y(y),
            z(z),
            Px(Px),
            Py(Py),
            Pz(Pz),
            energy(energy),
            generator_name(generator_name),
            pdg(pdg),
            process(process),
            track_id(track_id),
            truth_id(truth_id)
        {};

        // default constructor
        TrueParticle() : event(-1), x(0), y(0), z(0), Px(0), Py(0), Pz(0), energy(0), generator_name(""), pdg(-1), process(""),
            track_id(-1), truth_id(-1) {};

        // special constructor for when reading the files
        TrueParticle( 
            int event, 
            std::string generator_name, 
            int block_id
        ) : 
            event(event),
            generator_name(generator_name),
            pdg(block_id)
        {
            // set the rest to 0
            x = 0;
            y = 0;
            z = 0;
            Px = 0;
            Py = 0;
            Pz = 0;
            energy = 0;
            process = "";
        };
        
        // destructor
        ~TrueParticle() {
            if (neutrino != nullptr) {
                delete neutrino;
            }
        };

        // Setters
        void SetEvent(int event) { this->event = event; }
        void SetX(float x) { this->x = x; }
        void SetY(float y) { this->y = y; }
        void SetZ(float z) { this->z = z; }
        void SetPx(float Px) { this->Px = Px; }
        void SetPy(float Py) { this->Py = Py; }
        void SetPz(float Pz) { this->Pz = Pz; }
        void SetEnergy(float energy) { this->energy = energy; }
        void SetGeneratorName(std::string generator_name) { this->generator_name = generator_name; }
        void SetPdg(int pdg) { this->pdg = pdg; }
        void SetProcess(std::string process) { this->process = process; }
        void SetTrackId(int track_id) { this->track_id = track_id; }
        void SetTruthId(int truth_id) { this->truth_id = truth_id; }
        void SetNeutrino(Neutrino * neutrino) { this->neutrino = neutrino; }
        void SetTimeStart(double time_start) { this->time_start = time_start; }
        void SetTimeEnd(double time_end) { this->time_end = time_end; }
        // void SetChannels(std::vector<int> channels) { this->channels = channels; }

        // Getters
        int GetEvent() const { return event; }
        float GetX() const { return x; }
        float GetY() const { return y; }
        float GetZ() const { return z; }
        float GetPx() const { return Px; }
        float GetPy() const { return Py; }
        float GetPz() const { return Pz; }
        float GetEnergy() const { return energy; }
        std::string GetGeneratorName() const { return generator_name; }
        int GetPdg() const { return pdg; }
        std::string GetProcess() const { return process; }
        int GetTrackId() const { return track_id; }
        int GetTruthId() const { return truth_id; }
        Neutrino * GetNeutrino() const { return neutrino; }
        double GetTimeStart() const { return time_start; }
        double GetTimeEnd() const { return time_end; }
        std::vector<int> GetChannelStart() const { return channels; }

        void AddChannel(int channel){
            // check if the channel is already in the vector
            if (std::find(channels.begin(), channels.end(), channel) != channels.end()) return;
            channels.push_back(channel);
            // sort every time a new channel is added
            std::sort(channels.begin(), channels.end());
        };


    private:
        int event {0};
        float x {0.0f};
        float y {0.0f};
        float z {0.0f};
        float Px {0.0f};
        float Py {0.0f};
        float Pz {0.0f};
        float energy {0.0f};
        std::string generator_name {""};
        int pdg {0};
        std::string process {""};
        
        int track_id {-1}; // needed for association
        int truth_id {-1}; // needed for association
        Neutrino * neutrino = nullptr; // this is the neutrino that generated the particle, if any. For bkg, it will stay empty

        // these are needed to make associations
        double time_start {0};
        double time_end {INT_MAX};
        std::vector <int> channels = {};

};

#endif // TRUEPARTICLE_H